name: Auto_Build_ErfanGSIs
on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
 watch:
   types: [started]
env:
  ROM_URL: https://bigota.d.miui.com/V11.0.3.0.QEECNXM/miui_MIMIX3_V11.0.3.0.QEECNXM_4d73488207_10.0.zip
  ROM_NAME: MIUI
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
       - name: Fix apt problem and clean up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
       - name: Initialization environment
         run: |
           sudo -E apt-get -qq update
           sudo -E apt-get -y upgrade
           sudo -E apt-get -qq install git openjdk-8-jdk wget gzip bzip2 tar rar unzip
       - name: Clone ErfanGSI Source Code
         run: |
           git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       - name: Setting up ErfanGSI requirements
         run: |
           sudo chmod -R 777 ErfanGSIs
           cd ErfanGSIs
           sudo bash setup.sh
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       - name: Zip GSI  
         run: |
           mkdir final
           tar -Jcvf final/GSI.xz /home/runner/work/Auto_Build_ErfanGSIs/Auto_Build_ErfanGSIs/ErfanGSIs/output/
       - name: Upload GSI to BitSend
         uses: actions/upload-artifact@v2
         with:
           path: final/GSI.xz
           if-no-files-found: ERROR:No such file
