name: Get_ErfanGSIs_Source_Code

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# watch:
#   types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Check Out
      uses: actions/checkout@v2

    - name: Clone ErfanGSI Source Code & Zip
      run: |
#       下面这条是Erfan的源代码，默认使用
        git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
#       下面这条是我本人修改后的源代码，默认注释，如需使用请删除前面的 '#' 并注释掉上面的代码，否则会有冲突
#       git clone --recurse-submodules https://github.com/zhz8888/ErfanGSIs.git
        tar -Jcvf ErfanGSIs.tar.xz ErfanGSIs

    - name: Upload ErfanGSI Source Code
      uses: actions/upload-artifact@v2
      with:
        name: ErfanGSI-Source-Code
        path: ErfanGSIs.tar.xz
        if-no-files-found: error
